In [293]:
from pathlib import Path

import pandas as pd

In [294]:
RANDOM_SEED = 42
TEST_RATIO = 0.2
DATA_BASE_PATH = Path("./data")
# target - Price
# Decidir o que fazer com body

In [295]:
rent_path  = DATA_BASE_PATH / "apartments_for_rent_classified_10K.csv"

In [296]:
rent = pd.read_csv(rent_path, sep=";", encoding="latin1")
rent.head()

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,$790,Monthly,101,NaN,Washington,DC,38.9057,-76.9861,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,$425,Monthly,106,814 Schutte Rd,Evansville,IN,37.9680,-87.6621,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,"$1,390",Monthly,107,NaN,Arlington,VA,38.8910,-77.0816,RentLingo,1577359410
3,5659918074,housing/rent/apartment,Studio apartment 1717 12th Ave,"This unit is located at 1717 12th Ave, Seattle...",NaN,1.0,0.0,USD,No,Thumbnail,...,$925,Monthly,116,1717 12th Avenue,Seattle,WA,47.6160,-122.3275,RentLingo,1576667743
4,5668626759,housing/rent/apartment,"Studio apartment Washington Blvd, N Cleveland ...","This unit is located at Washington Blvd, N Cle...",NaN,NaN,0.0,USD,No,Thumbnail,...,$880,Monthly,125,NaN,Arlington,VA,38.8738,-77.1055,RentLingo,1577359401

In [297]:
prices = rent["price"]
print(prices)

0         790
1         425
2        1390
3         925
4         880
        ...
9995     6000
9996    25000
9997    11000
9998     4790
9999     1009
Name: price, Length: 10000, dtype: int64

In [298]:
rent = rent.drop(columns=["price_display"])
rent.head()

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,790,Monthly,101,NaN,Washington,DC,38.9057,-76.9861,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,425,Monthly,106,814 Schutte Rd,Evansville,IN,37.9680,-87.6621,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,1390,Monthly,107,NaN,Arlington,VA,38.8910,-77.0816,RentLingo,1577359410
3,5659918074,housing/rent/apartment,Studio apartment 1717 12th Ave,"This unit is located at 1717 12th Ave, Seattle...",NaN,1.0,0.0,USD,No,Thumbnail,...,925,Monthly,116,1717 12th Avenue,Seattle,WA,47.6160,-122.3275,RentLingo,1576667743
4,5668626759,housing/rent/apartment,"Studio apartment Washington Blvd, N Cleveland ...","This unit is located at Washington Blvd, N Cle...",NaN,NaN,0.0,USD,No,Thumbnail,...,880,Monthly,125,NaN,Arlington,VA,38.8738,-77.1055,RentLingo,1577359401

In [299]:
rent_amenities_median = rent["amenities"].str.split(",").str.len().median()
print(rent_amenities_median)

4.0

In [300]:
rent["amenities"] = rent["amenities"].fillna(rent_amenities_median)
print(rent["amenities"])

0                                                     4.0
1                                                     4.0
2                                                     4.0
3                                                     4.0
4                                                     4.0
                              ...
9995                                                  4.0
9996                                                  4.0
9997                                                  4.0
9998    Basketball,Cable or Satellite,Doorman,Hot Tub,...
9999                                       Gym,Patio/Deck
Name: amenities, Length: 10000, dtype: object

In [301]:
latitude_longitude = ["latitude", "longitude"]
rent = rent.drop(columns=latitude_longitude)    
print(rent)

              id                category  \
0     5668626895  housing/rent/apartment
1     5664597177  housing/rent/apartment
2     5668626833  housing/rent/apartment
3     5659918074  housing/rent/apartment
4     5668626759  housing/rent/apartment
...          ...                     ...
9995  5630240092  housing/rent/apartment
9996  5668640983  housing/rent/apartment
9997  5668643292  housing/rent/apartment
9998  5668662559  housing/rent/apartment
9999  5509132540  housing/rent/apartment

                                                  title  \
0     Studio apartment 2nd St NE, Uhland Terrace NE,...
1                     Studio apartment 814 Schutte Road
2     Studio apartment N Scott St, 14th St N, Arling...
3                        Studio apartment 1717 12th Ave
4     Studio apartment Washington Blvd, N Cleveland ...
...                                                 ...
9995                 Five BR 5407 Abbott Place - Abbott
9996                            Six BR 256 Las Entradas
9997                        Six BR 9908 Bentcross Drive
9998                        One BR in New York NY 10069
9999         Beautiful Lawrenceville Apartment for rent

                                                   body  \
0     This unit is located at second St NE, Uhland T...
1     This unit is located at 814 Schutte Road, Evan...
2     This unit is located at N Scott St, 14th St N,...
3     This unit is located at 1717 12th Ave, Seattle...
4     This unit is located at Washington Blvd, N Cle...
...                                                 ...
9995  This unit is located at 5407 Abbott Place - Ab...
9996  This unit is located at 256 Las Entradas, Mont...
9997  This unit is located at 9908 Bentcross Drive, ...
9998  Monthly Rent$4,605 -to $4,790AmenitiesThe Aldy...
9999  Square footage: 880 sq. feet, unit number: 150...

                                              amenities  bathrooms  bedrooms  \
0                                                   4.0        NaN       0.0
1                                                   4.0        NaN       1.0
2                                                   4.0        1.0       0.0
3                                                   4.0        1.0       0.0
4                                                   4.0        NaN       0.0
...                                                 ...        ...       ...
9995                                                4.0        4.0       5.0
9996                                                4.0        8.0       6.0
9997                                                4.0        8.5       6.0
9998  Basketball,Cable or Satellite,Doorman,Hot Tub,...        NaN       1.0
9999                                     Gym,Patio/Deck        1.0       1.0

     currency fee  has_photo pets_allowed  price price_type  square_feet  \
0         USD  No  Thumbnail          NaN    790    Monthly          101
1         USD  No  Thumbnail          NaN    425    Monthly          106
2         USD  No  Thumbnail          NaN   1390    Monthly          107
3         USD  No  Thumbnail          NaN    925    Monthly          116
4         USD  No  Thumbnail          NaN    880    Monthly          125
...       ...  ..        ...          ...    ...        ...          ...
9995      USD  No  Thumbnail          NaN   6000    Monthly         6300
9996      USD  No  Thumbnail          NaN  25000    Monthly         8716
9997      USD  No  Thumbnail          NaN  11000    Monthly        11318
9998      USD  No  Thumbnail          NaN   4790    Monthly        40000
9999      USD  No         No          NaN   1009    Monthly          880

                        address       cityname state        source        time
0                           NaN     Washington    DC     RentLingo  1577359415
1                814 Schutte Rd     Evansville    IN     RentLingo  1577017063
2                           NaN      Arlington    VA     RentLingo  1577359410
3              1717 12th Avenue        Seattle    WA     RentLingo  1576667743
4                           NaN      Arlington    VA     RentLingo  1577359401
...                         ...            ...   ...           ...         ...
9995  5407 Abbott Place  Abbott          Edina    MN     RentLingo  1575112975
9996           256 Las Entradas      Montecito    CA     RentLingo  1577360419
9997          9908 Bentcross Dr        Potomac    MD     RentLingo  1577360560
9998                        NaN       New York    NY      Listanza  1577362186
9999                        NaN  Lawrenceville    GA  RentDigs.com  1577362141

[10000 rows x 19 columns]

In [302]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

encoded = encoder.fit_transform(rent[["pets_allowed"]])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["pets_allowed"]))
encoded_df.index = rent.index

rent = pd.concat([rent.drop(columns=["pets_allowed"]), encoded_df], axis=1)

print(rent.head())

           id                category  \
0  5668626895  housing/rent/apartment
1  5664597177  housing/rent/apartment
2  5668626833  housing/rent/apartment
3  5659918074  housing/rent/apartment
4  5668626759  housing/rent/apartment

                                               title  \
0  Studio apartment 2nd St NE, Uhland Terrace NE,...
1                  Studio apartment 814 Schutte Road
2  Studio apartment N Scott St, 14th St N, Arling...
3                     Studio apartment 1717 12th Ave
4  Studio apartment Washington Blvd, N Cleveland ...

                                                body amenities  bathrooms  \
0  This unit is located at second St NE, Uhland T...       4.0        NaN
1  This unit is located at 814 Schutte Road, Evan...       4.0        NaN
2  This unit is located at N Scott St, 14th St N,...       4.0        1.0
3  This unit is located at 1717 12th Ave, Seattle...       4.0        1.0
4  This unit is located at Washington Blvd, N Cle...       4.0        NaN

   bedrooms currency fee  has_photo  ...  square_feet           address  \
0       0.0      USD  No  Thumbnail  ...          101               NaN
1       1.0      USD  No  Thumbnail  ...          106    814 Schutte Rd
2       0.0      USD  No  Thumbnail  ...          107               NaN
3       0.0      USD  No  Thumbnail  ...          116  1717 12th Avenue
4       0.0      USD  No  Thumbnail  ...          125               NaN

     cityname state     source        time pets_allowed_Cats  \
0  Washington    DC  RentLingo  1577359415               0.0
1  Evansville    IN  RentLingo  1577017063               0.0
2   Arlington    VA  RentLingo  1577359410               0.0
3     Seattle    WA  RentLingo  1576667743               0.0
4   Arlington    VA  RentLingo  1577359401               0.0

   pets_allowed_Cats,Dogs  pets_allowed_Dogs  pets_allowed_nan
0                     0.0                0.0               1.0
1                     0.0                0.0               1.0
2                     0.0                0.0               1.0
3                     0.0                0.0               1.0
4                     0.0                0.0               1.0

[5 rows x 22 columns]

In [303]:
print(rent.loc[rent["has_photo"] != "Thumbnail", "has_photo"].value_counts())

has_photo
Yes    909
No     184
Name: count, dtype: int64

In [304]:
import re

items = [
    "bedrooms", "refrigerator", "dishwasher", "range/oven", "micro wave", "freezer",
    "air conditioner", "washer and drier", "gas stove", "hard wood floors",
    "closets", "bed", "linens", "towels", "carpet", "curtains", "kitchen",
    "living room", "bath", "bathroom", "bedroom", "dining room", "beds"
]

def extract_quantity(text, item):
    pattern = rf'(\d+)\s*{re.escape(item)}|{re.escape(item)}\s*(\d+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        num = match.group(1) or match.group(2)
        return int(num)
    return 0

for item in items:
    col_name = item.lower().replace(" ", "_").replace("/", "_")
    rent[col_name] = rent["body"].fillna("").apply(lambda x: extract_quantity(x, item))

print(rent[[col_name for item in items for col_name in [item.lower().replace(" ", "_").replace("/", "_")]]].head())

   bedrooms  refrigerator  dishwasher  range_oven  micro_wave  freezer  \
0         0             0           0           0           0        0
1         0             0           0           0           0        0
2         0             0           0           0           0        0
3         0             0           0           0           0        0
4         0             0           0           0           0        0

   air_conditioner  washer_and_drier  gas_stove  hard_wood_floors  ...  \
0                0                 0          0                 0  ...
1                0                 0          0                 0  ...
2                0                 0          0                 0  ...
3                0                 0          0                 0  ...
4                0                 0          0                 0  ...

   towels  carpet  curtains  kitchen  living_room  bath  bathroom  bedroom  \
0       0       0         0        0            0     0         0        0
1       0       0         0        0            0     0         0        0
2       0       0         0        0            0     0         0        0
3       0       0         0        0            0     0         0        0
4       0       0         0        0            0     0         0        0

   dining_room  beds
0            0     0
1            0     1
2            0     0
3            0     0
4            0     0

[5 rows x 23 columns]

In [305]:
rent["has_photo"] = rent["has_photo"].apply(lambda x: 1 if x == "Yes" else 0)
print(rent["has_photo"])

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: has_photo, Length: 10000, dtype: int64